# Generated by Django 3.0.7 on 2020-06-26 07:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='month',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='image',
            name='quarter',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to=api.models.upload_location),
        ),
        migrations.AlterField(
            model_name='image',
            name='year',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
